import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import Nav from "./navigation/nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  profile,
}: Readonly<{
  children: React.ReactNode
  profile: React.ReactNode
}>) {
  const isAdmin = true;
  return (
    <html lang="en">
      <body
        // className={inter.className}
      >
        <nav>
          <ul>
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <Link href={"/about"}>About</Link>
          </ul>
        </nav>
        <Nav />
        {children}
        {isAdmin && profile}
      </body>
    </html>
  );
}
